name: 'Bitrise Build Runner'
description: 'Run Bitrise build as a step in GitHub Actions workflow.'
author: 'p-mazhnik'

branding:
  icon: 'server'
  color: 'purple'

inputs:
  bitrise-token:
    description: 'User-generated personal access token or Workspace API token'
    required: false
  bitrise-app-slug:
    description: 'Bitrise App slug'
    required: true
  bitrise-build-trigger-token:
    description:
      "Bitrise Build trigger token. Can be used as alternative to
      'bitrise-token' when 'listen: false'. 'bitrise-token' takes priority."
    required: false
  bitrise-workflow:
    description:
      'The name of the workflow you want to trigger (mutually exclusive with
      bitrise-pipeline)'
    required: false
  bitrise-pipeline:
    description:
      'The name of the pipeline you want to trigger (mutually exclusive with
      bitrise-workflow)'
    required: false
  listen:
    description:
      'Set to `true` if you want to listen for the build logs and wait for build
      completion. Not supported with bitrise-pipeline'
    required: false
    default: 'false'
  update-interval:
    description: 'How often the action calls the API for updates, seconds'
    required: false
    default: '15'
  skip-git-status-report:
    description: 'Set to `true` if you want do skip git status report'
    required: false
    default: 'false'
  env-vars-for-bitrise:
    description:
      'Comma separated list of environment variables to send to Bitrise'
    required: false
  stop-on-signals:
    description:
      'Comma separated list of process signals on which to stop the build.
      Default is SIGINT.'
    required: false
    default: 'SIGINT'
  branch-override:
    description: 'Overrides branch provided to Bitrise'
    required: false
  commit-override:
    description: 'Overrides commit provided to Bitrise'
    required: false
outputs:
  bitrise-build-id:
    description: 'The Bitrise Build ID for this build.'
  bitrise-build-url:
    description: 'The Bitrise Build url for this build.'
runs:
  using: node20
  main: dist/index.js
