##
# Publish new action tag(s) for downstream consumption
##
name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Release with semantic tag like v1.0.3
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        id: install
        run: npm ci

      # Compile dist/index.js and bundle with action.yml
      # Force push major and minor tags, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
